# Generated by Django 3.0.5 on 2020-04-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='languages',
            field=models.CharField(choices=[('4', 'Django'), ('2', 'Java'), ('1', 'python'), ('3', 'C++')], max_length=4),
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(max_length=30)),
                ('User', models.ManyToManyField(to='signup.User')),
            ],
        ),
    ]
