# Generated by Django 2.2.1 on 2020-04-22 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20200419_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='languages',
        ),
    ]
