# Generated by Django 2.2.1 on 2020-04-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_remove_user_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chosen',
            field=models.BooleanField(default=False),
        ),
    ]
