# Generated by Django 2.2.1 on 2020-05-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20200430_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='User',
            field=models.ManyToManyField(related_name='skill', to='signup.User'),
        ),
    ]
