# Generated by Django 2.2.1 on 2020-05-24 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_auto_20200506_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='member',
        ),
        migrations.AddField(
            model_name='squad',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='signup.User'),
        ),
    ]
