# Generated by Django 2.2.1 on 2020-05-25 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_auto_20200524_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squad',
            name='member',
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='signup.Squad'),
        ),
    ]
